import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { createFFmpeg, fetchFile } from '@ffmpeg/ffmpeg';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';

const WasmComponent = dynamic({
  loader: async () => {
    const ffmpeg = createFFmpeg({ log: true });
    await ffmpeg.load();
    
    // eslint-disable-next-line react/display-name
    return () => <div>Done!</div>
  },
},{ ssr: false })

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <WasmComponent/>
      </main>
    </div>
  )
}

export default Home
